### ISSUE TITLE
hitting "end turn" while the "create a new building" tooltip is open doesn't update "build" buttons state

### ISSUE THREAD

**Issue by bnjbvr** [adngdb/village-builder#1]
STR
===

- do not have enough resources to build X, but make sure that you have them next turn
- open the "create a new building" tooltip
- click "end turn"

Expected
===

The building of X should be possible, ie the button should not be disabled anymore.

Observed
===

It is still disabled.

This is a critical and very urgent issue that must be fixed yesterday. If it is not, then I'll switch to Chrome!!1!

**Comment by adngdb** [comment]
Thank you for reporting this issue, which our team obviously already knew of. We underestimated its importance and the impact it would have on our players. We're going to fix it as soon as humanly possible. Please DO NOT switch to Chrome, or you might catch a very bad disease like the Covid19 or the SIDA. Stay safe.
