### ISSUE TITLE
[CRITICAL] Upgrade arrow shows up when my production buildings are at their highest level

### ISSUE THREAD

**Issue by aurelien-defossez** [adngdb/village-builder#5]
If a production building (e.g. sawmill) is at level 3, which seems to be the maximum, the update animated arrow still shows up, and if I click on the building, I can't do anything more.

Severity: Critical, I can't continue to work properly while these icons taunt me into doing something I can't do

![chrome_2020-05-11_14-04-55](https://user-images.githubusercontent.com/319900/81559823-6eb2b280-9390-11ea-8538-c280b23997f8.png)

**Comment by adngdb** [comment]
What build are you using? I deployed a corrected build on Saturday here: http://games.lqbs.fr/village/day5/ with a fix for exactly this problem. And I haven't seen that problem anymore since then, on the day5 build or on the [latest build](http://games.lqbs.fr/village/latest/).

**Comment by aurelien-defossez** [comment]
It was on http://games.lqbs.fr/village/day5/ unless I screwed up.

**Comment by adngdb** [comment]
Pretty sure this is already fixed. Maybe you had an old build in your cache, since I re-published it at some point with fixes? Anyway, I haven't been able to reproduce on recent builds. :-)

**Comment by adngdb** [comment]
My bad: it's still reproducible on the day5 build, but I fixed it afterwards with https://github.com/adngdb/village-builder/commit/e434f7fc3bef4f91f0d73358c7f5daf88819de68 and I guess I haven't deployed that particular fix. Please play the [latest build](http://games.lqbs.fr/village/latest/) instead! :grin:
